# Generated by Django 3.2.3 on 2021-05-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eunoia', '0004_auto_20210528_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentTest',
        ),
    ]
